

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: build
  jobs:
  - job: build_planetpowershell
    displayName: 'Build PlanetPowerShell'
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - task: NuGetToolInstaller@0
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        testAssemblyVer2: |
          **\$(BuildConfiguration)\*test*.dll
          !**\obj\**
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'planetpowershell'
  - job: validate_armtemplate
    displayName: 'Validate ARM Template'
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Sponsorship - Dev(5e32aad4-771d-4098-98d5-6cda4f387656)'
        subscriptionId: '5e32aad4-771d-4098-98d5-6cda4f387656'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'PlanetPowerShell-Dev-RG'
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/src/AzureDeploy/azuredeploy.json'
        overrideParameters: '$(DevAzureParameters)'
        deploymentMode: 'Validation'

- stage: release
  dependsOn: build
  jobs:
  - deployment: deploy_development
    displayName: 'Deploy Development'
    pool:
      vmImage: VS2017-Win2016
    environment: 'PlanetPowerShell Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - download: current
            artifact: 'planetpowershell'
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure Sponsorship - Dev(5e32aad4-771d-4098-98d5-6cda4f387656)'
              subscriptionId: '5e32aad4-771d-4098-98d5-6cda4f387656'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'PlanetPowerShell-Dev-RG'
              location: 'East US 2'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/src/AzureDeploy/azuredeploy.json'
              overrideParameters: '$(DevAzureParameters)'
              deploymentMode: 'Incremental'
  - deployment: deploy_production
    displayName: 'Deploy Production'
    dependsOn: deploy_development
    pool:
      vmImage: VS2017-Win2016
    environment: 'PlanetPowerShell Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - download: current
            artifact: 'planetpowershell'
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure Sponsorship - Prod(8ab775cc-fea2-4356-9307-a9b79faab5ed)'
              subscriptionId: '8ab775cc-fea2-4356-9307-a9b79faab5ed'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'PlanetPowerShell-Prod-RG'
              location: 'East US 2'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/src/AzureDeploy/azuredeploy.json'
              overrideParameters: '$(ProdAzureParameters)'
              deploymentMode: 'Incremental'