

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactname: 'planetpowershell'

stages:

- stage: build
  jobs:
  - job: build_planetpowershell
    displayName: 'Build PlanetPowerShell'
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - task: NuGetToolInstaller@0
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        testAssemblyVer2: |
          **\$(BuildConfiguration)\*test*.dll
          !**\obj\**
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: AzSKARMTemplateChecker@4
      inputs:
        ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)/src/AzureDeploy/azuredeploy.json'
    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Sponsorship - Dev(5e32aad4-771d-4098-98d5-6cda4f387656)'
        subscriptionId: '5e32aad4-771d-4098-98d5-6cda4f387656'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'PlanetPowerShell-Dev-RG'
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/src/AzureDeploy/azuredeploy.json'
        deploymentMode: 'Validation'